### ISSUE TITLE
Subgraph can`t display label text

### ISSUE THREAD

**Issue by TihonchukArtyom89** [microsoft/automatic-graph-layout#377] opened 2024-09-24 08:19 UTC
Hi! I am using wpfgraphcontrol and place subgraph on a graph. My code is based on a sample WpfApplicationSample and it do not display label text.
Codebehind:

      public partial class MainWindow : Window
      {
              public MainWindow()
              {
                     InitializeComponent();
              }
     private void Window_Loaded(object sender, RoutedEventArgs e)
     {
           GraphViewer graphViewer = new GraphViewer();
           Graph graph = new("graph_id");
           graphViewer.BindToPanel(graphViewerPanel);
           var a = new drawingNode("A");
           var b = new drawingNode("B");
           var c = new drawingNode("C");  
           var d = new drawingNode("D");
           graph.AddNode(a);
           graph.AddNode(b);
           graph.AddNode(c);   
           graph.AddNode(d);   
           graph.AddEdge(a.Id, b.Id);
           graph.AddEdge(b.Id, c.Id);
           graph.AddEdge(d.Id, c.Id);
           var subgraph = new Subgraph("subgraph1");
           graph.RootSubgraph.AddSubgraph(subgraph);
           subgraph.Label.Text = "text for subgraph";
           subgraph.AddNode(a);
           subgraph.AddNode(b);
           subgraph.AddNode(c);
           graphViewer.Graph = graph;
    }

Result:
![result](https://github.com/user-attachments/assets/f0a60c9e-ca81-4beb-955e-7b384f3db75f)

**Comment by MartinBischoff** [comment] 2024-11-23 18:15
I ran into the same problem today and can confirm this issue. Anyone found a workaround? Will this be fixed in the next version?

**Comment by levnach** [comment] 2024-11-25 21:59
It works for me in the current version built from the sources.
![Image](https://github.com/user-attachments/assets/b0571e39-20c4-46e6-ad30-820eccad4b10)

**Comment by MartinBischoff** [comment] 2024-11-26 11:56
Thank you @levnach  for this hint.
My local build of the tip of the master branch resolves the issue.
Looking forward to replace my local build with the next released version.

This issue is resolved from my side. Feel free to close it.

**Comment by levnach** [comment] 2024-12-14 17:11
This functionality is supported by NuGet https://www.nuget.org/packages/Msagl.WpfGraphControl/1.2.1.

**Closed** 2024-12-14 17:11 UTC

**Comment by MartinBischoff** [comment] 2024-12-16 09:52
Confirmed. This issue is resolved with the latest NuGet release.
No local build required anymore.
Thank you @levnach ! 🙇
